version: "3.8"

services:

  bot:
    build: .
    command: sh -c "alembic revision --autogenerate && alembic upgrade head && python preloads.py && python bot.py && uvicorn fastapi_app:app --host 0.0.0.0 --port 8000"
    container_name: fb-bot
    volumes:
      - .:/bot
    env_file:
      - .env.bot
    ports:
      - "8001:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine3.18
    container_name: postgres-fb-bot
    env_file:
      - .env.postgres
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.11-alpine3.18
    hostname: redis
    container_name: redis-bot

  celery-worker:
    build: .
    command: celery -A src.settings:celery worker -l INFO
    container_name: celery-worker
    volumes:
      - .:/bot
    env_file:
      - .env.bot
    depends_on:
      - postgres
      - redis
      - celery-beat
      - bot

  celery-beat:
    build: .
    command: celery -A src.settings:celery beat -l INFO
    container_name: celery-beat
    volumes:
      - .:/bot
    env_file:
      - .env.bot
    depends_on:
      - postgres
      - redis
      - bot



