version: "3.8"

services:

  bot:
    build: .
    command: sh -c "alembic revision --autogenerate && alembic upgrade head && python preloads.py && python bot.py & python app.py && uvicorn fastapi_app:app --host 0.0.0.0 --port 8000"
    container_name: fb-bot
    volumes:
      - .:/bot
    environment:
      - BOT_TOKEN=6366199783:AAF0vbIzEo3g4hO7riXs-q0dFZEOdb6_sBM
      - DATABASE_URL=postgresql://bot:qwerty@postgres:5432/bot2
    ports:
      - "8001:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:15-alpine3.18
    container_name: postgres-fb-bot
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=bot
      - POSTGRES_DB=bot2
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432



