"""empty message

Revision ID: 1439bd0c7d65
Revises: fce0bcbfd82f
Create Date: 2023-08-06 18:12:57.193946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1439bd0c7d65'
down_revision = 'fce0bcbfd82f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searching_links',
    sa.Column('link', sa.VARCHAR(length=512), nullable=True),
    sa.Column('geo', sa.VARCHAR(length=256), nullable=True),
    sa.Column('query', sa.VARCHAR(length=256), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searching_links')
    # ### end Alembic commands ###
