"""empty message

Revision ID: 1dc2d508d90c
Revises: 
Create Date: 2023-08-11 17:04:19.814737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc2d508d90c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('symbol', sa.VARCHAR(length=32), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility',
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fb_user',
    sa.Column('login', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('land',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('link_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_group',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('keyword',
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('product_link', sa.VARCHAR(length=512), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.INTEGER(), nullable=False),
    sa.Column('in_month', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('expose_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['currency'], ['currency.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('product_link')
    )
    op.create_table('search_link',
    sa.Column('link', sa.VARCHAR(length=512), nullable=False),
    sa.Column('land_id', sa.BIGINT(), nullable=False),
    sa.Column('query', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['land.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('tg_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_group.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('picture',
    sa.Column('link', sa.VARCHAR(length=512), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_facility',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_facility',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_land',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('land_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['land.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_link',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('link_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['search_link.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tg_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fb_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_users',
    sa.Column('login', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='fb_users_pkey')
    )
    op.drop_table('user_link')
    op.drop_table('user_land')
    op.drop_table('user_facility')
    op.drop_table('product_facility')
    op.drop_table('picture')
    op.drop_table('tg_user')
    op.drop_table('search_link')
    op.drop_table('product')
    op.drop_table('keyword')
    op.drop_table('user_group')
    op.drop_table('land')
    op.drop_table('fb_user')
    op.drop_table('facility')
    op.drop_table('currency')
    # ### end Alembic commands ###
