"""empty message

Revision ID: 74efd8c776db
Revises: df6bd043202f
Create Date: 2023-08-01 20:46:30.945839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74efd8c776db'
down_revision = 'df6bd043202f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
