"""empty message

Revision ID: 86df172987f5
Revises: 1dc2d508d90c
Create Date: 2023-08-12 10:44:03.192546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86df172987f5'
down_revision = '1dc2d508d90c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('username', sa.VARCHAR(length=64), nullable=False))
    op.add_column('tg_user', sa.Column('access_expire', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'tg_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_user', type_='unique')
    op.drop_column('tg_user', 'access_expire')
    op.drop_column('tg_user', 'username')
    # ### end Alembic commands ###
