"""empty message

Revision ID: 9d0946f704cd
Revises: 1439bd0c7d65
Create Date: 2023-08-07 12:27:54.865409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0946f704cd'
down_revision = '1439bd0c7d65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'fb_users', ['login'])
    op.create_unique_constraint(None, 'searching_links', ['link'])
    op.add_column('users', sa.Column('searching_links_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'searching_links', ['searching_links_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'searching_links_id')
    op.drop_constraint(None, 'searching_links', type_='unique')
    op.drop_constraint(None, 'fb_users', type_='unique')
    # ### end Alembic commands ###
