"""empty message

Revision ID: c99f7e3a7243
Revises: 86df172987f5
Create Date: 2023-08-12 17:04:20.309705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99f7e3a7243'
down_revision = '86df172987f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('land', sa.INTEGER()))
    op.create_foreign_key(None, 'product', 'land', ['land'], ['id'], ondelete='RESTRICT')
    op.add_column('tg_user', sa.Column('show_products', sa.BOOLEAN(), nullable=True))
    op.alter_column('tg_user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tg_user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('tg_user', 'show_products')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'land')
    # ### end Alembic commands ###
