"""empty message

Revision ID: dab645f3650f
Revises: 
Create Date: 2023-08-01 19:26:35.984367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab645f3650f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('product_link', sa.VARCHAR(length=512), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('price', sa.VARCHAR(length=128), nullable=True),
    sa.Column('product_prop', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('pictures', sa.TEXT(), nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('current', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_link')
    )
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('group', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
