"""empty message

Revision ID: fce0bcbfd82f
Revises: 74efd8c776db
Create Date: 2023-08-06 18:00:47.259528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce0bcbfd82f'
down_revision = '74efd8c776db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fb_users',
    sa.Column('login', sa.VARCHAR(length=128), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fb_users')
    # ### end Alembic commands ###
